#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zirsakht_stock
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="stock")]
	public partial class lqStockDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblSite(tblSite instance);
    partial void UpdatetblSite(tblSite instance);
    partial void DeletetblSite(tblSite instance);
    partial void InserttblType(tblType instance);
    partial void UpdatetblType(tblType instance);
    partial void DeletetblType(tblType instance);
    partial void InserttblEquipment(tblEquipment instance);
    partial void UpdatetblEquipment(tblEquipment instance);
    partial void DeletetblEquipment(tblEquipment instance);
    partial void InserttblUnit(tblUnit instance);
    partial void UpdatetblUnit(tblUnit instance);
    partial void DeletetblUnit(tblUnit instance);
    partial void Inserttblcategory(tblcategory instance);
    partial void Updatetblcategory(tblcategory instance);
    partial void Deletetblcategory(tblcategory instance);
    partial void InserttblSubCategory(tblSubCategory instance);
    partial void UpdatetblSubCategory(tblSubCategory instance);
    partial void DeletetblSubCategory(tblSubCategory instance);
    partial void InserttblAnbar(tblAnbar instance);
    partial void UpdatetblAnbar(tblAnbar instance);
    partial void DeletetblAnbar(tblAnbar instance);
    partial void InserttblRecieved(tblRecieved instance);
    partial void UpdatetblRecieved(tblRecieved instance);
    partial void DeletetblRecieved(tblRecieved instance);
    partial void InserttblDelivered(tblDelivered instance);
    partial void UpdatetblDelivered(tblDelivered instance);
    partial void DeletetblDelivered(tblDelivered instance);
    partial void InserttblResid(tblResid instance);
    partial void UpdatetblResid(tblResid instance);
    partial void DeletetblResid(tblResid instance);
    #endregion
		
		public lqStockDataContext() : 
				base(global::zirsakht_stock.Properties.Settings.Default.stockConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public lqStockDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lqStockDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lqStockDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lqStockDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblSite> tblSites
		{
			get
			{
				return this.GetTable<tblSite>();
			}
		}
		
		public System.Data.Linq.Table<tblType> tblTypes
		{
			get
			{
				return this.GetTable<tblType>();
			}
		}
		
		public System.Data.Linq.Table<tblEquipment> tblEquipments
		{
			get
			{
				return this.GetTable<tblEquipment>();
			}
		}
		
		public System.Data.Linq.Table<tblUnit> tblUnits
		{
			get
			{
				return this.GetTable<tblUnit>();
			}
		}
		
		public System.Data.Linq.Table<tblcategory> tblcategories
		{
			get
			{
				return this.GetTable<tblcategory>();
			}
		}
		
		public System.Data.Linq.Table<tblSubCategory> tblSubCategories
		{
			get
			{
				return this.GetTable<tblSubCategory>();
			}
		}
		
		public System.Data.Linq.Table<vwKarde> vwKardes
		{
			get
			{
				return this.GetTable<vwKarde>();
			}
		}
		
		public System.Data.Linq.Table<vwkardex> vwkardexes
		{
			get
			{
				return this.GetTable<vwkardex>();
			}
		}
		
		public System.Data.Linq.Table<tblAnbar> tblAnbars
		{
			get
			{
				return this.GetTable<tblAnbar>();
			}
		}
		
		public System.Data.Linq.Table<tblRecieved> tblRecieveds
		{
			get
			{
				return this.GetTable<tblRecieved>();
			}
		}
		
		public System.Data.Linq.Table<tblDelivered> tblDelivereds
		{
			get
			{
				return this.GetTable<tblDelivered>();
			}
		}
		
		public System.Data.Linq.Table<tblResid> tblResids
		{
			get
			{
				return this.GetTable<tblResid>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CalculateTotal", IsComposable=true)]
		public System.Nullable<int> CalculateTotal([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceID", DbType="Int")] System.Nullable<int> deviceID)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deviceID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getkala_inanbar", IsComposable=true)]
		public IQueryable<getkala_inanbarResult> getkala_inanbar()
		{
			return this.CreateMethodCallQuery<getkala_inanbarResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CalculateTotalbydate", IsComposable=true)]
		public System.Nullable<int> CalculateTotalbydate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceID", DbType="Int")] System.Nullable<int> deviceID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string date)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deviceID, date).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Calculatesadereh", IsComposable=true)]
		public System.Nullable<int> Calculatesadereh([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceID", DbType="Int")] System.Nullable<int> deviceID)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deviceID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fnGetResidNO", IsComposable=true)]
		public System.Nullable<int> fnGetResidNO()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Calculatevaredeh", IsComposable=true)]
		public System.Nullable<int> Calculatevaredeh([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeviceID", DbType="Int")] System.Nullable<int> deviceID)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deviceID).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSites")]
	public partial class tblSite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Ostan;
		
		private EntitySet<tblDelivered> _tblDelivereds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnOstanChanging(string value);
    partial void OnOstanChanged();
    #endregion
		
		public tblSite()
		{
			this._tblDelivereds = new EntitySet<tblDelivered>(new Action<tblDelivered>(this.attach_tblDelivereds), new Action<tblDelivered>(this.detach_tblDelivereds));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ostan", DbType="NVarChar(50)")]
		public string Ostan
		{
			get
			{
				return this._Ostan;
			}
			set
			{
				if ((this._Ostan != value))
				{
					this.OnOstanChanging(value);
					this.SendPropertyChanging();
					this._Ostan = value;
					this.SendPropertyChanged("Ostan");
					this.OnOstanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSite_tblDelivered", Storage="_tblDelivereds", ThisKey="ID", OtherKey="SiteID")]
		public EntitySet<tblDelivered> tblDelivereds
		{
			get
			{
				return this._tblDelivereds;
			}
			set
			{
				this._tblDelivereds.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDelivereds(tblDelivered entity)
		{
			this.SendPropertyChanging();
			entity.tblSite = this;
		}
		
		private void detach_tblDelivereds(tblDelivered entity)
		{
			this.SendPropertyChanging();
			entity.tblSite = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTypes")]
	public partial class tblType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TypeDesc;
		
		private EntitySet<tblEquipment> _tblEquipments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTypeDescChanging(string value);
    partial void OnTypeDescChanged();
    #endregion
		
		public tblType()
		{
			this._tblEquipments = new EntitySet<tblEquipment>(new Action<tblEquipment>(this.attach_tblEquipments), new Action<tblEquipment>(this.detach_tblEquipments));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeDesc", DbType="NVarChar(50)")]
		public string TypeDesc
		{
			get
			{
				return this._TypeDesc;
			}
			set
			{
				if ((this._TypeDesc != value))
				{
					this.OnTypeDescChanging(value);
					this.SendPropertyChanging();
					this._TypeDesc = value;
					this.SendPropertyChanged("TypeDesc");
					this.OnTypeDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblType_tblEquipment", Storage="_tblEquipments", ThisKey="ID", OtherKey="Type")]
		public EntitySet<tblEquipment> tblEquipments
		{
			get
			{
				return this._tblEquipments;
			}
			set
			{
				this._tblEquipments.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblEquipments(tblEquipment entity)
		{
			this.SendPropertyChanging();
			entity.tblType = this;
		}
		
		private void detach_tblEquipments(tblEquipment entity)
		{
			this.SendPropertyChanging();
			entity.tblType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEquipments")]
	public partial class tblEquipment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Partnumber;
		
		private System.Nullable<int> _Type;
		
		private System.Nullable<int> _UnitID;
		
		private EntitySet<tblRecieved> _tblRecieveds;
		
		private EntitySet<tblDelivered> _tblDelivereds;
		
		private EntityRef<tblType> _tblType;
		
		private EntityRef<tblUnit> _tblUnit;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPartnumberChanging(string value);
    partial void OnPartnumberChanged();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    partial void OnUnitIDChanging(System.Nullable<int> value);
    partial void OnUnitIDChanged();
    #endregion
		
		public tblEquipment()
		{
			this._tblRecieveds = new EntitySet<tblRecieved>(new Action<tblRecieved>(this.attach_tblRecieveds), new Action<tblRecieved>(this.detach_tblRecieveds));
			this._tblDelivereds = new EntitySet<tblDelivered>(new Action<tblDelivered>(this.attach_tblDelivereds), new Action<tblDelivered>(this.detach_tblDelivereds));
			this._tblType = default(EntityRef<tblType>);
			this._tblUnit = default(EntityRef<tblUnit>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Partnumber", DbType="NVarChar(50)")]
		public string Partnumber
		{
			get
			{
				return this._Partnumber;
			}
			set
			{
				if ((this._Partnumber != value))
				{
					this.OnPartnumberChanging(value);
					this.SendPropertyChanging();
					this._Partnumber = value;
					this.SendPropertyChanged("Partnumber");
					this.OnPartnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					if (this._tblType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitID", DbType="Int")]
		public System.Nullable<int> UnitID
		{
			get
			{
				return this._UnitID;
			}
			set
			{
				if ((this._UnitID != value))
				{
					if (this._tblUnit.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUnitIDChanging(value);
					this.SendPropertyChanging();
					this._UnitID = value;
					this.SendPropertyChanged("UnitID");
					this.OnUnitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEquipment_tblRecieved", Storage="_tblRecieveds", ThisKey="ID", OtherKey="EquipID")]
		public EntitySet<tblRecieved> tblRecieveds
		{
			get
			{
				return this._tblRecieveds;
			}
			set
			{
				this._tblRecieveds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEquipment_tblDelivered", Storage="_tblDelivereds", ThisKey="ID", OtherKey="EquipID")]
		public EntitySet<tblDelivered> tblDelivereds
		{
			get
			{
				return this._tblDelivereds;
			}
			set
			{
				this._tblDelivereds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblType_tblEquipment", Storage="_tblType", ThisKey="Type", OtherKey="ID", IsForeignKey=true)]
		public tblType tblType
		{
			get
			{
				return this._tblType.Entity;
			}
			set
			{
				tblType previousValue = this._tblType.Entity;
				if (((previousValue != value) 
							|| (this._tblType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblType.Entity = null;
						previousValue.tblEquipments.Remove(this);
					}
					this._tblType.Entity = value;
					if ((value != null))
					{
						value.tblEquipments.Add(this);
						this._Type = value.ID;
					}
					else
					{
						this._Type = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblType");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUnit_tblEquipment", Storage="_tblUnit", ThisKey="UnitID", OtherKey="ID", IsForeignKey=true)]
		public tblUnit tblUnit
		{
			get
			{
				return this._tblUnit.Entity;
			}
			set
			{
				tblUnit previousValue = this._tblUnit.Entity;
				if (((previousValue != value) 
							|| (this._tblUnit.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUnit.Entity = null;
						previousValue.tblEquipments.Remove(this);
					}
					this._tblUnit.Entity = value;
					if ((value != null))
					{
						value.tblEquipments.Add(this);
						this._UnitID = value.ID;
					}
					else
					{
						this._UnitID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblUnit");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblRecieveds(tblRecieved entity)
		{
			this.SendPropertyChanging();
			entity.tblEquipment = this;
		}
		
		private void detach_tblRecieveds(tblRecieved entity)
		{
			this.SendPropertyChanging();
			entity.tblEquipment = null;
		}
		
		private void attach_tblDelivereds(tblDelivered entity)
		{
			this.SendPropertyChanging();
			entity.tblEquipment = this;
		}
		
		private void detach_tblDelivereds(tblDelivered entity)
		{
			this.SendPropertyChanging();
			entity.tblEquipment = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUnits")]
	public partial class tblUnit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Unit;
		
		private string _Description;
		
		private EntitySet<tblEquipment> _tblEquipments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUnitChanging(string value);
    partial void OnUnitChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public tblUnit()
		{
			this._tblEquipments = new EntitySet<tblEquipment>(new Action<tblEquipment>(this.attach_tblEquipments), new Action<tblEquipment>(this.detach_tblEquipments));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(50)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this.OnUnitChanging(value);
					this.SendPropertyChanging();
					this._Unit = value;
					this.SendPropertyChanged("Unit");
					this.OnUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NChar(10)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUnit_tblEquipment", Storage="_tblEquipments", ThisKey="ID", OtherKey="UnitID")]
		public EntitySet<tblEquipment> tblEquipments
		{
			get
			{
				return this._tblEquipments;
			}
			set
			{
				this._tblEquipments.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblEquipments(tblEquipment entity)
		{
			this.SendPropertyChanging();
			entity.tblUnit = this;
		}
		
		private void detach_tblEquipments(tblEquipment entity)
		{
			this.SendPropertyChanging();
			entity.tblUnit = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblcategory")]
	public partial class tblcategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Title;
		
		private EntitySet<tblSubCategory> _tblSubCategories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    #endregion
		
		public tblcategory()
		{
			this._tblSubCategories = new EntitySet<tblSubCategory>(new Action<tblSubCategory>(this.attach_tblSubCategories), new Action<tblSubCategory>(this.detach_tblSubCategories));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblcategory_tblSubCategory", Storage="_tblSubCategories", ThisKey="ID", OtherKey="catID")]
		public EntitySet<tblSubCategory> tblSubCategories
		{
			get
			{
				return this._tblSubCategories;
			}
			set
			{
				this._tblSubCategories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSubCategories(tblSubCategory entity)
		{
			this.SendPropertyChanging();
			entity.tblcategory = this;
		}
		
		private void detach_tblSubCategories(tblSubCategory entity)
		{
			this.SendPropertyChanging();
			entity.tblcategory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSubCategory")]
	public partial class tblSubCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _title;
		
		private int _catID;
		
		private EntitySet<tblResid> _tblResids;
		
		private EntityRef<tblcategory> _tblcategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncatIDChanging(int value);
    partial void OncatIDChanged();
    #endregion
		
		public tblSubCategory()
		{
			this._tblResids = new EntitySet<tblResid>(new Action<tblResid>(this.attach_tblResids), new Action<tblResid>(this.detach_tblResids));
			this._tblcategory = default(EntityRef<tblcategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catID", DbType="Int NOT NULL")]
		public int catID
		{
			get
			{
				return this._catID;
			}
			set
			{
				if ((this._catID != value))
				{
					if (this._tblcategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncatIDChanging(value);
					this.SendPropertyChanging();
					this._catID = value;
					this.SendPropertyChanged("catID");
					this.OncatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSubCategory_tblResid", Storage="_tblResids", ThisKey="ID", OtherKey="kharidType")]
		public EntitySet<tblResid> tblResids
		{
			get
			{
				return this._tblResids;
			}
			set
			{
				this._tblResids.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblcategory_tblSubCategory", Storage="_tblcategory", ThisKey="catID", OtherKey="ID", IsForeignKey=true)]
		public tblcategory tblcategory
		{
			get
			{
				return this._tblcategory.Entity;
			}
			set
			{
				tblcategory previousValue = this._tblcategory.Entity;
				if (((previousValue != value) 
							|| (this._tblcategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblcategory.Entity = null;
						previousValue.tblSubCategories.Remove(this);
					}
					this._tblcategory.Entity = value;
					if ((value != null))
					{
						value.tblSubCategories.Add(this);
						this._catID = value.ID;
					}
					else
					{
						this._catID = default(int);
					}
					this.SendPropertyChanged("tblcategory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblResids(tblResid entity)
		{
			this.SendPropertyChanging();
			entity.tblSubCategory = this;
		}
		
		private void detach_tblResids(tblResid entity)
		{
			this.SendPropertyChanging();
			entity.tblSubCategory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwKardes")]
	public partial class vwKarde
	{
		
		private int _id;
		
		private string _partnumber;
		
		private string _date;
		
		private string _sdate;
		
		private string _vdate;
		
		private System.Nullable<long> _tedad;
		
		private System.Nullable<long> _sadereh;
		
		private System.Nullable<int> _varedeh;
		
		private System.Nullable<int> _equipid;
		
		private string _dahande;
		
		private string _receivedby;
		
		private int _status;
		
		private System.Nullable<int> _mj;
		
		private System.Nullable<System.DateTime> _dateadded;
		
		public vwKarde()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partnumber", DbType="NVarChar(50)")]
		public string partnumber
		{
			get
			{
				return this._partnumber;
			}
			set
			{
				if ((this._partnumber != value))
				{
					this._partnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdate", DbType="NVarChar(10)")]
		public string sdate
		{
			get
			{
				return this._sdate;
			}
			set
			{
				if ((this._sdate != value))
				{
					this._sdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vdate", DbType="NVarChar(50)")]
		public string vdate
		{
			get
			{
				return this._vdate;
			}
			set
			{
				if ((this._vdate != value))
				{
					this._vdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedad", DbType="BigInt")]
		public System.Nullable<long> tedad
		{
			get
			{
				return this._tedad;
			}
			set
			{
				if ((this._tedad != value))
				{
					this._tedad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sadereh", DbType="BigInt")]
		public System.Nullable<long> sadereh
		{
			get
			{
				return this._sadereh;
			}
			set
			{
				if ((this._sadereh != value))
				{
					this._sadereh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_varedeh", DbType="Int")]
		public System.Nullable<int> varedeh
		{
			get
			{
				return this._varedeh;
			}
			set
			{
				if ((this._varedeh != value))
				{
					this._varedeh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipid", DbType="Int")]
		public System.Nullable<int> equipid
		{
			get
			{
				return this._equipid;
			}
			set
			{
				if ((this._equipid != value))
				{
					this._equipid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dahande", DbType="NVarChar(50)")]
		public string dahande
		{
			get
			{
				return this._dahande;
			}
			set
			{
				if ((this._dahande != value))
				{
					this._dahande = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receivedby", DbType="NVarChar(50)")]
		public string receivedby
		{
			get
			{
				return this._receivedby;
			}
			set
			{
				if ((this._receivedby != value))
				{
					this._receivedby = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mj", DbType="Int")]
		public System.Nullable<int> mj
		{
			get
			{
				return this._mj;
			}
			set
			{
				if ((this._mj != value))
				{
					this._mj = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateadded", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateadded
		{
			get
			{
				return this._dateadded;
			}
			set
			{
				if ((this._dateadded != value))
				{
					this._dateadded = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwkardex")]
	public partial class vwkardex
	{
		
		private int _id;
		
		private string _partnumber;
		
		private string _date;
		
		private string _sdate;
		
		private string _vdate;
		
		private System.Nullable<long> _tedad;
		
		private System.Nullable<long> _sadereh;
		
		private System.Nullable<int> _varedeh;
		
		private System.Nullable<int> _equipid;
		
		private string _dahande;
		
		private string _receivedby;
		
		private int _status;
		
		private System.Nullable<System.DateTime> _dateadded;
		
		public vwkardex()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partnumber", DbType="NVarChar(50)")]
		public string partnumber
		{
			get
			{
				return this._partnumber;
			}
			set
			{
				if ((this._partnumber != value))
				{
					this._partnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="NVarChar(50)")]
		public string date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdate", DbType="NVarChar(10)")]
		public string sdate
		{
			get
			{
				return this._sdate;
			}
			set
			{
				if ((this._sdate != value))
				{
					this._sdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vdate", DbType="NVarChar(50)")]
		public string vdate
		{
			get
			{
				return this._vdate;
			}
			set
			{
				if ((this._vdate != value))
				{
					this._vdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedad", DbType="BigInt")]
		public System.Nullable<long> tedad
		{
			get
			{
				return this._tedad;
			}
			set
			{
				if ((this._tedad != value))
				{
					this._tedad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sadereh", DbType="BigInt")]
		public System.Nullable<long> sadereh
		{
			get
			{
				return this._sadereh;
			}
			set
			{
				if ((this._sadereh != value))
				{
					this._sadereh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_varedeh", DbType="Int")]
		public System.Nullable<int> varedeh
		{
			get
			{
				return this._varedeh;
			}
			set
			{
				if ((this._varedeh != value))
				{
					this._varedeh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipid", DbType="Int")]
		public System.Nullable<int> equipid
		{
			get
			{
				return this._equipid;
			}
			set
			{
				if ((this._equipid != value))
				{
					this._equipid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dahande", DbType="NVarChar(50)")]
		public string dahande
		{
			get
			{
				return this._dahande;
			}
			set
			{
				if ((this._dahande != value))
				{
					this._dahande = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receivedby", DbType="NVarChar(50)")]
		public string receivedby
		{
			get
			{
				return this._receivedby;
			}
			set
			{
				if ((this._receivedby != value))
				{
					this._receivedby = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
		public int status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateadded", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateadded
		{
			get
			{
				return this._dateadded;
			}
			set
			{
				if ((this._dateadded != value))
				{
					this._dateadded = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAnbar")]
	public partial class tblAnbar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Title;
		
		private string _Address;
		
		private EntitySet<tblResid> _tblResids;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    #endregion
		
		public tblAnbar()
		{
			this._tblResids = new EntitySet<tblResid>(new Action<tblResid>(this.attach_tblResids), new Action<tblResid>(this.detach_tblResids));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAnbar_tblResid", Storage="_tblResids", ThisKey="ID", OtherKey="AnbarID")]
		public EntitySet<tblResid> tblResids
		{
			get
			{
				return this._tblResids;
			}
			set
			{
				this._tblResids.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblResids(tblResid entity)
		{
			this.SendPropertyChanging();
			entity.tblAnbar = this;
		}
		
		private void detach_tblResids(tblResid entity)
		{
			this.SendPropertyChanging();
			entity.tblAnbar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblRecieved")]
	public partial class tblRecieved : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PartNumber;
		
		private System.Nullable<int> _Tedad;
		
		private System.Nullable<int> _EquipID;
		
		private string _EndofGarranty;
		
		private string _ResidNo;
		
		private System.Nullable<System.DateTime> _dateadded;
		
		private EntityRef<tblEquipment> _tblEquipment;
		
		private EntityRef<tblResid> _tblResid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPartNumberChanging(string value);
    partial void OnPartNumberChanged();
    partial void OnTedadChanging(System.Nullable<int> value);
    partial void OnTedadChanged();
    partial void OnEquipIDChanging(System.Nullable<int> value);
    partial void OnEquipIDChanged();
    partial void OnEndofGarrantyChanging(string value);
    partial void OnEndofGarrantyChanged();
    partial void OnResidNoChanging(string value);
    partial void OnResidNoChanged();
    partial void OndateaddedChanging(System.Nullable<System.DateTime> value);
    partial void OndateaddedChanged();
    #endregion
		
		public tblRecieved()
		{
			this._tblEquipment = default(EntityRef<tblEquipment>);
			this._tblResid = default(EntityRef<tblResid>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartNumber", DbType="NVarChar(50)")]
		public string PartNumber
		{
			get
			{
				return this._PartNumber;
			}
			set
			{
				if ((this._PartNumber != value))
				{
					this.OnPartNumberChanging(value);
					this.SendPropertyChanging();
					this._PartNumber = value;
					this.SendPropertyChanged("PartNumber");
					this.OnPartNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tedad", DbType="Int")]
		public System.Nullable<int> Tedad
		{
			get
			{
				return this._Tedad;
			}
			set
			{
				if ((this._Tedad != value))
				{
					this.OnTedadChanging(value);
					this.SendPropertyChanging();
					this._Tedad = value;
					this.SendPropertyChanged("Tedad");
					this.OnTedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipID", DbType="Int")]
		public System.Nullable<int> EquipID
		{
			get
			{
				return this._EquipID;
			}
			set
			{
				if ((this._EquipID != value))
				{
					if (this._tblEquipment.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEquipIDChanging(value);
					this.SendPropertyChanging();
					this._EquipID = value;
					this.SendPropertyChanged("EquipID");
					this.OnEquipIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndofGarranty", DbType="NVarChar(50)")]
		public string EndofGarranty
		{
			get
			{
				return this._EndofGarranty;
			}
			set
			{
				if ((this._EndofGarranty != value))
				{
					this.OnEndofGarrantyChanging(value);
					this.SendPropertyChanging();
					this._EndofGarranty = value;
					this.SendPropertyChanged("EndofGarranty");
					this.OnEndofGarrantyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResidNo", DbType="NVarChar(50)")]
		public string ResidNo
		{
			get
			{
				return this._ResidNo;
			}
			set
			{
				if ((this._ResidNo != value))
				{
					if (this._tblResid.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnResidNoChanging(value);
					this.SendPropertyChanging();
					this._ResidNo = value;
					this.SendPropertyChanged("ResidNo");
					this.OnResidNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateadded", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateadded
		{
			get
			{
				return this._dateadded;
			}
			set
			{
				if ((this._dateadded != value))
				{
					this.OndateaddedChanging(value);
					this.SendPropertyChanging();
					this._dateadded = value;
					this.SendPropertyChanged("dateadded");
					this.OndateaddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEquipment_tblRecieved", Storage="_tblEquipment", ThisKey="EquipID", OtherKey="ID", IsForeignKey=true)]
		public tblEquipment tblEquipment
		{
			get
			{
				return this._tblEquipment.Entity;
			}
			set
			{
				tblEquipment previousValue = this._tblEquipment.Entity;
				if (((previousValue != value) 
							|| (this._tblEquipment.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblEquipment.Entity = null;
						previousValue.tblRecieveds.Remove(this);
					}
					this._tblEquipment.Entity = value;
					if ((value != null))
					{
						value.tblRecieveds.Add(this);
						this._EquipID = value.ID;
					}
					else
					{
						this._EquipID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblEquipment");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblResid_tblRecieved", Storage="_tblResid", ThisKey="ResidNo", OtherKey="ResidNo", IsForeignKey=true)]
		public tblResid tblResid
		{
			get
			{
				return this._tblResid.Entity;
			}
			set
			{
				tblResid previousValue = this._tblResid.Entity;
				if (((previousValue != value) 
							|| (this._tblResid.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblResid.Entity = null;
						previousValue.tblRecieveds.Remove(this);
					}
					this._tblResid.Entity = value;
					if ((value != null))
					{
						value.tblRecieveds.Add(this);
						this._ResidNo = value.ResidNo;
					}
					else
					{
						this._ResidNo = default(string);
					}
					this.SendPropertyChanged("tblResid");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDelivered")]
	public partial class tblDelivered : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PartNumber;
		
		private string _Description;
		
		private string _Agent;
		
		private string _Date;
		
		private string _ReceivedBy;
		
		private System.Nullable<int> _SiteID;
		
		private System.Nullable<long> _Tedad;
		
		private System.Nullable<int> _EquipID;
		
		private string _HavalehNO;
		
		private string _RequestedBy;
		
		private System.Nullable<System.DateTime> _dateadded;
		
		private string _Amvalno;
		
		private bool _Temp;
		
		private EntityRef<tblEquipment> _tblEquipment;
		
		private EntityRef<tblSite> _tblSite;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPartNumberChanging(string value);
    partial void OnPartNumberChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAgentChanging(string value);
    partial void OnAgentChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnReceivedByChanging(string value);
    partial void OnReceivedByChanged();
    partial void OnSiteIDChanging(System.Nullable<int> value);
    partial void OnSiteIDChanged();
    partial void OnTedadChanging(System.Nullable<long> value);
    partial void OnTedadChanged();
    partial void OnEquipIDChanging(System.Nullable<int> value);
    partial void OnEquipIDChanged();
    partial void OnHavalehNOChanging(string value);
    partial void OnHavalehNOChanged();
    partial void OnRequestedByChanging(string value);
    partial void OnRequestedByChanged();
    partial void OndateaddedChanging(System.Nullable<System.DateTime> value);
    partial void OndateaddedChanged();
    partial void OnAmvalnoChanging(string value);
    partial void OnAmvalnoChanged();
    partial void OnTempChanging(bool value);
    partial void OnTempChanged();
    #endregion
		
		public tblDelivered()
		{
			this._tblEquipment = default(EntityRef<tblEquipment>);
			this._tblSite = default(EntityRef<tblSite>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartNumber", DbType="NVarChar(50)")]
		public string PartNumber
		{
			get
			{
				return this._PartNumber;
			}
			set
			{
				if ((this._PartNumber != value))
				{
					this.OnPartNumberChanging(value);
					this.SendPropertyChanging();
					this._PartNumber = value;
					this.SendPropertyChanged("PartNumber");
					this.OnPartNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agent", DbType="NVarChar(50)")]
		public string Agent
		{
			get
			{
				return this._Agent;
			}
			set
			{
				if ((this._Agent != value))
				{
					this.OnAgentChanging(value);
					this.SendPropertyChanging();
					this._Agent = value;
					this.SendPropertyChanged("Agent");
					this.OnAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="NChar(10)")]
		public string Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceivedBy", DbType="NVarChar(50)")]
		public string ReceivedBy
		{
			get
			{
				return this._ReceivedBy;
			}
			set
			{
				if ((this._ReceivedBy != value))
				{
					this.OnReceivedByChanging(value);
					this.SendPropertyChanging();
					this._ReceivedBy = value;
					this.SendPropertyChanged("ReceivedBy");
					this.OnReceivedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteID", DbType="Int")]
		public System.Nullable<int> SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					if (this._tblSite.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tedad", DbType="BigInt")]
		public System.Nullable<long> Tedad
		{
			get
			{
				return this._Tedad;
			}
			set
			{
				if ((this._Tedad != value))
				{
					this.OnTedadChanging(value);
					this.SendPropertyChanging();
					this._Tedad = value;
					this.SendPropertyChanged("Tedad");
					this.OnTedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipID", DbType="Int")]
		public System.Nullable<int> EquipID
		{
			get
			{
				return this._EquipID;
			}
			set
			{
				if ((this._EquipID != value))
				{
					if (this._tblEquipment.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEquipIDChanging(value);
					this.SendPropertyChanging();
					this._EquipID = value;
					this.SendPropertyChanged("EquipID");
					this.OnEquipIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HavalehNO", DbType="NVarChar(50)")]
		public string HavalehNO
		{
			get
			{
				return this._HavalehNO;
			}
			set
			{
				if ((this._HavalehNO != value))
				{
					this.OnHavalehNOChanging(value);
					this.SendPropertyChanging();
					this._HavalehNO = value;
					this.SendPropertyChanged("HavalehNO");
					this.OnHavalehNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestedBy", DbType="VarChar(50)")]
		public string RequestedBy
		{
			get
			{
				return this._RequestedBy;
			}
			set
			{
				if ((this._RequestedBy != value))
				{
					this.OnRequestedByChanging(value);
					this.SendPropertyChanging();
					this._RequestedBy = value;
					this.SendPropertyChanged("RequestedBy");
					this.OnRequestedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateadded", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateadded
		{
			get
			{
				return this._dateadded;
			}
			set
			{
				if ((this._dateadded != value))
				{
					this.OndateaddedChanging(value);
					this.SendPropertyChanging();
					this._dateadded = value;
					this.SendPropertyChanged("dateadded");
					this.OndateaddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amvalno", DbType="NVarChar(50)")]
		public string Amvalno
		{
			get
			{
				return this._Amvalno;
			}
			set
			{
				if ((this._Amvalno != value))
				{
					this.OnAmvalnoChanging(value);
					this.SendPropertyChanging();
					this._Amvalno = value;
					this.SendPropertyChanged("Amvalno");
					this.OnAmvalnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temp", DbType="Bit NOT NULL")]
		public bool Temp
		{
			get
			{
				return this._Temp;
			}
			set
			{
				if ((this._Temp != value))
				{
					this.OnTempChanging(value);
					this.SendPropertyChanging();
					this._Temp = value;
					this.SendPropertyChanged("Temp");
					this.OnTempChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEquipment_tblDelivered", Storage="_tblEquipment", ThisKey="EquipID", OtherKey="ID", IsForeignKey=true)]
		public tblEquipment tblEquipment
		{
			get
			{
				return this._tblEquipment.Entity;
			}
			set
			{
				tblEquipment previousValue = this._tblEquipment.Entity;
				if (((previousValue != value) 
							|| (this._tblEquipment.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblEquipment.Entity = null;
						previousValue.tblDelivereds.Remove(this);
					}
					this._tblEquipment.Entity = value;
					if ((value != null))
					{
						value.tblDelivereds.Add(this);
						this._EquipID = value.ID;
					}
					else
					{
						this._EquipID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblEquipment");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSite_tblDelivered", Storage="_tblSite", ThisKey="SiteID", OtherKey="ID", IsForeignKey=true)]
		public tblSite tblSite
		{
			get
			{
				return this._tblSite.Entity;
			}
			set
			{
				tblSite previousValue = this._tblSite.Entity;
				if (((previousValue != value) 
							|| (this._tblSite.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSite.Entity = null;
						previousValue.tblDelivereds.Remove(this);
					}
					this._tblSite.Entity = value;
					if ((value != null))
					{
						value.tblDelivereds.Add(this);
						this._SiteID = value.ID;
					}
					else
					{
						this._SiteID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblSite");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblResid")]
	public partial class tblResid : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _Date;
		
		private string _Ersal;
		
		private string _Description;
		
		private string _ReceivedBy;
		
		private bool _kharid;
		
		private int _kharidType;
		
		private string _ContractNO;
		
		private string _RequestNo;
		
		private System.Nullable<int> _AnbarID;
		
		private string _ResidNo;
		
		private bool _issued;
		
		private System.Nullable<System.DateTime> _dateadded;
		
		private bool _Returned;
		
		private EntitySet<tblRecieved> _tblRecieveds;
		
		private EntityRef<tblAnbar> _tblAnbar;
		
		private EntityRef<tblSubCategory> _tblSubCategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnDateChanging(string value);
    partial void OnDateChanged();
    partial void OnErsalChanging(string value);
    partial void OnErsalChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnReceivedByChanging(string value);
    partial void OnReceivedByChanged();
    partial void OnkharidChanging(bool value);
    partial void OnkharidChanged();
    partial void OnkharidTypeChanging(int value);
    partial void OnkharidTypeChanged();
    partial void OnContractNOChanging(string value);
    partial void OnContractNOChanged();
    partial void OnRequestNoChanging(string value);
    partial void OnRequestNoChanged();
    partial void OnAnbarIDChanging(System.Nullable<int> value);
    partial void OnAnbarIDChanged();
    partial void OnResidNoChanging(string value);
    partial void OnResidNoChanged();
    partial void OnissuedChanging(bool value);
    partial void OnissuedChanged();
    partial void OndateaddedChanging(System.Nullable<System.DateTime> value);
    partial void OndateaddedChanged();
    partial void OnReturnedChanging(bool value);
    partial void OnReturnedChanged();
    #endregion
		
		public tblResid()
		{
			this._tblRecieveds = new EntitySet<tblRecieved>(new Action<tblRecieved>(this.attach_tblRecieveds), new Action<tblRecieved>(this.detach_tblRecieveds));
			this._tblAnbar = default(EntityRef<tblAnbar>);
			this._tblSubCategory = default(EntityRef<tblSubCategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="NVarChar(50)")]
		public string Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ersal", DbType="NVarChar(50)")]
		public string Ersal
		{
			get
			{
				return this._Ersal;
			}
			set
			{
				if ((this._Ersal != value))
				{
					this.OnErsalChanging(value);
					this.SendPropertyChanging();
					this._Ersal = value;
					this.SendPropertyChanged("Ersal");
					this.OnErsalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(300)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceivedBy", DbType="NVarChar(50)")]
		public string ReceivedBy
		{
			get
			{
				return this._ReceivedBy;
			}
			set
			{
				if ((this._ReceivedBy != value))
				{
					this.OnReceivedByChanging(value);
					this.SendPropertyChanging();
					this._ReceivedBy = value;
					this.SendPropertyChanged("ReceivedBy");
					this.OnReceivedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kharid", DbType="Bit NOT NULL")]
		public bool kharid
		{
			get
			{
				return this._kharid;
			}
			set
			{
				if ((this._kharid != value))
				{
					this.OnkharidChanging(value);
					this.SendPropertyChanging();
					this._kharid = value;
					this.SendPropertyChanged("kharid");
					this.OnkharidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kharidType", DbType="Int NOT NULL")]
		public int kharidType
		{
			get
			{
				return this._kharidType;
			}
			set
			{
				if ((this._kharidType != value))
				{
					if (this._tblSubCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkharidTypeChanging(value);
					this.SendPropertyChanging();
					this._kharidType = value;
					this.SendPropertyChanged("kharidType");
					this.OnkharidTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractNO", DbType="NVarChar(50)")]
		public string ContractNO
		{
			get
			{
				return this._ContractNO;
			}
			set
			{
				if ((this._ContractNO != value))
				{
					this.OnContractNOChanging(value);
					this.SendPropertyChanging();
					this._ContractNO = value;
					this.SendPropertyChanged("ContractNO");
					this.OnContractNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestNo", DbType="NVarChar(50)")]
		public string RequestNo
		{
			get
			{
				return this._RequestNo;
			}
			set
			{
				if ((this._RequestNo != value))
				{
					this.OnRequestNoChanging(value);
					this.SendPropertyChanging();
					this._RequestNo = value;
					this.SendPropertyChanged("RequestNo");
					this.OnRequestNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnbarID", DbType="Int")]
		public System.Nullable<int> AnbarID
		{
			get
			{
				return this._AnbarID;
			}
			set
			{
				if ((this._AnbarID != value))
				{
					if (this._tblAnbar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAnbarIDChanging(value);
					this.SendPropertyChanging();
					this._AnbarID = value;
					this.SendPropertyChanged("AnbarID");
					this.OnAnbarIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResidNo", DbType="NVarChar(50)")]
		public string ResidNo
		{
			get
			{
				return this._ResidNo;
			}
			set
			{
				if ((this._ResidNo != value))
				{
					this.OnResidNoChanging(value);
					this.SendPropertyChanging();
					this._ResidNo = value;
					this.SendPropertyChanged("ResidNo");
					this.OnResidNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_issued", DbType="Bit NOT NULL")]
		public bool issued
		{
			get
			{
				return this._issued;
			}
			set
			{
				if ((this._issued != value))
				{
					this.OnissuedChanging(value);
					this.SendPropertyChanging();
					this._issued = value;
					this.SendPropertyChanged("issued");
					this.OnissuedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateadded", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateadded
		{
			get
			{
				return this._dateadded;
			}
			set
			{
				if ((this._dateadded != value))
				{
					this.OndateaddedChanging(value);
					this.SendPropertyChanging();
					this._dateadded = value;
					this.SendPropertyChanged("dateadded");
					this.OndateaddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Returned", DbType="Bit NOT NULL")]
		public bool Returned
		{
			get
			{
				return this._Returned;
			}
			set
			{
				if ((this._Returned != value))
				{
					this.OnReturnedChanging(value);
					this.SendPropertyChanging();
					this._Returned = value;
					this.SendPropertyChanged("Returned");
					this.OnReturnedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblResid_tblRecieved", Storage="_tblRecieveds", ThisKey="ResidNo", OtherKey="ResidNo")]
		public EntitySet<tblRecieved> tblRecieveds
		{
			get
			{
				return this._tblRecieveds;
			}
			set
			{
				this._tblRecieveds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblAnbar_tblResid", Storage="_tblAnbar", ThisKey="AnbarID", OtherKey="ID", IsForeignKey=true)]
		public tblAnbar tblAnbar
		{
			get
			{
				return this._tblAnbar.Entity;
			}
			set
			{
				tblAnbar previousValue = this._tblAnbar.Entity;
				if (((previousValue != value) 
							|| (this._tblAnbar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblAnbar.Entity = null;
						previousValue.tblResids.Remove(this);
					}
					this._tblAnbar.Entity = value;
					if ((value != null))
					{
						value.tblResids.Add(this);
						this._AnbarID = value.ID;
					}
					else
					{
						this._AnbarID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblAnbar");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSubCategory_tblResid", Storage="_tblSubCategory", ThisKey="kharidType", OtherKey="ID", IsForeignKey=true)]
		public tblSubCategory tblSubCategory
		{
			get
			{
				return this._tblSubCategory.Entity;
			}
			set
			{
				tblSubCategory previousValue = this._tblSubCategory.Entity;
				if (((previousValue != value) 
							|| (this._tblSubCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSubCategory.Entity = null;
						previousValue.tblResids.Remove(this);
					}
					this._tblSubCategory.Entity = value;
					if ((value != null))
					{
						value.tblResids.Add(this);
						this._kharidType = value.ID;
					}
					else
					{
						this._kharidType = default(int);
					}
					this.SendPropertyChanged("tblSubCategory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblRecieveds(tblRecieved entity)
		{
			this.SendPropertyChanging();
			entity.tblResid = this;
		}
		
		private void detach_tblRecieveds(tblRecieved entity)
		{
			this.SendPropertyChanging();
			entity.tblResid = null;
		}
	}
	
	public partial class getkala_inanbarResult
	{
		
		private System.Nullable<int> _equipid;
		
		public getkala_inanbarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipid", DbType="Int")]
		public System.Nullable<int> equipid
		{
			get
			{
				return this._equipid;
			}
			set
			{
				if ((this._equipid != value))
				{
					this._equipid = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
